export {TextInputComponent as TextInput } from './TextInput';
export {PassInputComponent as PassInput } from './TextInput';
export {default as Alert } from './Alert';
export {default as Link } from './Link';
export {default as TouchableOpacity } from './TouchableOpacity';
export {default as ScrollView } from './ScrollView';
export {default as DocumentPicker } from './DocumentPicker';
export {default as ImagePicker } from './ImagePicker';
export {default as Switch } from './Switch';
export {default as ActivityIndicator } from './ActivityIndicator';
export {Single as Picker } from './Picker';
export {default as CheckBox } from './Checkbox';
export {Multi as MultiSelect } from './Picker';
export {default as ViewContainer} from './ViewContainer';
export {default as KeyboardAvoidingView} from './KeyboardAvoidingView';
